"""
Known IMAP providers database.
Maps email domain -> IMAP server configuration.
"""

KNOWN_PROVIDERS = {
    # ── Google ──────────────────────────────────────────────────────────────
    "gmail.com":            {"host": "imap.gmail.com",               "port": 993},
    "googlemail.com":       {"host": "imap.gmail.com",               "port": 993},
    # ── Microsoft ────────────────────────────────────────────────────────────
    "outlook.com":          {"host": "outlook.office365.com",        "port": 993},
    "hotmail.com":          {"host": "outlook.office365.com",        "port": 993},
    "hotmail.fr":           {"host": "outlook.office365.com",        "port": 993},
    "hotmail.co.uk":        {"host": "outlook.office365.com",        "port": 993},
    "hotmail.de":           {"host": "outlook.office365.com",        "port": 993},
    "hotmail.es":           {"host": "outlook.office365.com",        "port": 993},
    "hotmail.it":           {"host": "outlook.office365.com",        "port": 993},
    "hotmail.be":           {"host": "outlook.office365.com",        "port": 993},
    "hotmail.nl":           {"host": "outlook.office365.com",        "port": 993},
    "hotmail.ca":           {"host": "outlook.office365.com",        "port": 993},
    "live.com":             {"host": "outlook.office365.com",        "port": 993},
    "live.fr":              {"host": "outlook.office365.com",        "port": 993},
    "live.co.uk":           {"host": "outlook.office365.com",        "port": 993},
    "live.de":              {"host": "outlook.office365.com",        "port": 993},
    "live.nl":              {"host": "outlook.office365.com",        "port": 993},
    "live.be":              {"host": "outlook.office365.com",        "port": 993},
    "live.ca":              {"host": "outlook.office365.com",        "port": 993},
    "live.it":              {"host": "outlook.office365.com",        "port": 993},
    "live.com.au":          {"host": "outlook.office365.com",        "port": 993},
    "msn.com":              {"host": "outlook.office365.com",        "port": 993},
    "passport.com":         {"host": "outlook.office365.com",        "port": 993},
    # ── Yahoo ─────────────────────────────────────────────────────────────────
    "yahoo.com":            {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.fr":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.co.uk":          {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.de":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.es":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.it":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.com.au":         {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.ca":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.com.br":         {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.com.ar":         {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.com.mx":         {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.gr":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.pt":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.ro":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.pl":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.se":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.dk":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.no":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.ie":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "yahoo.in":             {"host": "imap.mail.yahoo.com",          "port": 993},
    "ymail.com":            {"host": "imap.mail.yahoo.com",          "port": 993},
    "rocketmail.com":       {"host": "imap.mail.yahoo.com",          "port": 993},
    # ── Apple ─────────────────────────────────────────────────────────────────
    "icloud.com":           {"host": "imap.mail.me.com",             "port": 993},
    "me.com":               {"host": "imap.mail.me.com",             "port": 993},
    "mac.com":              {"host": "imap.mail.me.com",             "port": 993},
    # ── AOL ───────────────────────────────────────────────────────────────────
    "aol.com":              {"host": "imap.aol.com",                 "port": 993},
    "aol.fr":               {"host": "imap.aol.com",                 "port": 993},
    "aol.co.uk":            {"host": "imap.aol.com",                 "port": 993},
    "aol.de":               {"host": "imap.aol.com",                 "port": 993},
    "aim.com":              {"host": "imap.aol.com",                 "port": 993},
    "netscape.net":         {"host": "imap.aol.com",                 "port": 993},
    # ── Yandex ────────────────────────────────────────────────────────────────
    "yandex.ru":            {"host": "imap.yandex.ru",               "port": 993},
    "yandex.com":           {"host": "imap.yandex.com",              "port": 993},
    "yandex.by":            {"host": "imap.yandex.ru",               "port": 993},
    "yandex.kz":            {"host": "imap.yandex.ru",               "port": 993},
    "yandex.ua":            {"host": "imap.yandex.ru",               "port": 993},
    "ya.ru":                {"host": "imap.yandex.ru",               "port": 993},
    # ── Mail.ru ───────────────────────────────────────────────────────────────
    "mail.ru":              {"host": "imap.mail.ru",                 "port": 993},
    "inbox.ru":             {"host": "imap.mail.ru",                 "port": 993},
    "list.ru":              {"host": "imap.mail.ru",                 "port": 993},
    "bk.ru":                {"host": "imap.mail.ru",                 "port": 993},
    "internet.ru":          {"host": "imap.mail.ru",                 "port": 993},
    # ── GMX ───────────────────────────────────────────────────────────────────
    "gmx.com":              {"host": "imap.gmx.com",                 "port": 993},
    "gmx.net":              {"host": "imap.gmx.net",                 "port": 993},
    "gmx.de":               {"host": "imap.gmx.net",                 "port": 993},
    "gmx.at":               {"host": "imap.gmx.net",                 "port": 993},
    "gmx.ch":               {"host": "imap.gmx.net",                 "port": 993},
    "gmx.fr":               {"host": "imap.gmx.fr",                  "port": 993},
    "gmx.us":               {"host": "imap.gmx.com",                 "port": 993},
    "gmx.org":              {"host": "imap.gmx.com",                 "port": 993},
    "gmx.co.uk":            {"host": "imap.gmx.co.uk",               "port": 993},
    # ── WEB.DE ────────────────────────────────────────────────────────────────
    "web.de":               {"host": "imap.web.de",                  "port": 993},
    # ── T-Online ──────────────────────────────────────────────────────────────
    "t-online.de":          {"host": "secureimap.t-online.de",       "port": 993},
    # ── Freenet ───────────────────────────────────────────────────────────────
    "freenet.de":           {"host": "mx.freenet.de",                "port": 993},
    # ── 1&1 Ionos ─────────────────────────────────────────────────────────────
    "1und1.de":             {"host": "imap.1und1.de",                "port": 993},
    "ionos.de":             {"host": "imap.ionos.de",                "port": 993},
    "ionos.com":            {"host": "imap.ionos.com",               "port": 993},
    # ── Zoho ──────────────────────────────────────────────────────────────────
    "zoho.com":             {"host": "imap.zoho.com",                "port": 993},
    "zohomail.com":         {"host": "imap.zoho.com",                "port": 993},
    "zoho.eu":              {"host": "imappro.zoho.eu",              "port": 993},
    # ── Fastmail ──────────────────────────────────────────────────────────────
    "fastmail.com":         {"host": "imap.fastmail.com",            "port": 993},
    "fastmail.fm":          {"host": "imap.fastmail.com",            "port": 993},
    "fastmail.net":         {"host": "imap.fastmail.com",            "port": 993},
    "fastmail.org":         {"host": "imap.fastmail.com",            "port": 993},
    "fastmail.to":          {"host": "imap.fastmail.com",            "port": 993},
    # ── Posteo ────────────────────────────────────────────────────────────────
    "posteo.de":            {"host": "posteo.de",                    "port": 993},
    "posteo.net":           {"host": "posteo.de",                    "port": 993},
    # ── OVH / Infomaniak ──────────────────────────────────────────────────────
    "ovh.com":              {"host": "ssl0.ovh.net",                 "port": 993},
    "ovh.net":              {"host": "ssl0.ovh.net",                 "port": 993},
    "infomaniak.com":       {"host": "mail.infomaniak.com",          "port": 993},
    # ── French ISPs ───────────────────────────────────────────────────────────
    "orange.fr":            {"host": "imap.orange.fr",               "port": 993},
    "wanadoo.fr":           {"host": "imap.orange.fr",               "port": 993},
    "sfr.fr":               {"host": "imap.sfr.fr",                  "port": 993},
    "neuf.fr":              {"host": "imap.sfr.fr",                  "port": 993},
    "club-internet.fr":     {"host": "imap.sfr.fr",                  "port": 993},
    "free.fr":              {"host": "imap.free.fr",                 "port": 993},
    "laposte.net":          {"host": "imap.laposte.net",             "port": 993},
    "bbox.fr":              {"host": "imap.bbox.fr",                 "port": 993},
    "bouyguestelecom.fr":   {"host": "imap.bbox.fr",                 "port": 993},
    "numericable.fr":       {"host": "mail.numericable.fr",          "port": 993},
    "aliceadsl.fr":         {"host": "imap.aliceadsl.fr",            "port": 993},
    "noos.fr":              {"host": "imap.sfr.fr",                  "port": 993},
    "9online.fr":           {"host": "imap.sfr.fr",                  "port": 993},
    # ── UK ISPs ───────────────────────────────────────────────────────────────
    "btinternet.com":       {"host": "mail.btinternet.com",          "port": 993},
    "btopenworld.com":      {"host": "mail.btinternet.com",          "port": 993},
    "sky.com":              {"host": "imap.sky.com",                  "port": 993},
    "virginmedia.com":      {"host": "imap.virginmedia.com",         "port": 993},
    "talktalk.net":         {"host": "imap.talktalk.net",            "port": 993},
    "ntlworld.com":         {"host": "imap.virginmedia.com",         "port": 993},
    # ── US ISPs ───────────────────────────────────────────────────────────────
    "comcast.net":          {"host": "imap.comcast.net",             "port": 993},
    "verizon.net":          {"host": "incoming.verizon.net",         "port": 993},
    "att.net":              {"host": "imap.mail.att.net",            "port": 993},
    "sbcglobal.net":        {"host": "imap.mail.att.net",            "port": 993},
    "bellsouth.net":        {"host": "imap.mail.att.net",            "port": 993},
    "cox.net":              {"host": "imap.cox.net",                  "port": 993},
    "earthlink.net":        {"host": "imap.earthlink.net",           "port": 993},
    "charter.net":          {"host": "imap.spectrum.net",            "port": 993},
    "spectrum.net":         {"host": "imap.spectrum.net",            "port": 993},
    "optonline.net":        {"host": "mail.optonline.net",           "port": 993},
    "roadrunner.com":       {"host": "imap.spectrum.net",            "port": 993},
    # ── Rambler ───────────────────────────────────────────────────────────────
    "rambler.ru":           {"host": "imap.rambler.ru",              "port": 993},
    "lenta.ru":             {"host": "imap.rambler.ru",              "port": 993},
    "myrambler.ru":         {"host": "imap.rambler.ru",              "port": 993},
    # ── Misc ──────────────────────────────────────────────────────────────────
    "prodigy.net":          {"host": "imap.prodigy.net",             "port": 993},
    "naver.com":            {"host": "imap.naver.com",               "port": 993},
    "daum.net":             {"host": "imap.daum.net",                "port": 993},
    "hanmail.net":          {"host": "imap.daum.net",                "port": 993},
    "163.com":              {"host": "imap.163.com",                 "port": 993},
    "126.com":              {"host": "imap.126.com",                 "port": 993},
    "qq.com":               {"host": "imap.qq.com",                  "port": 993},
    "sina.com":             {"host": "imap.sina.com",                "port": 993},
    "sina.cn":              {"host": "imap.sina.com",                "port": 993},
    "sohu.com":             {"host": "imap.sohu.com",                "port": 993},
    "139.com":              {"host": "imap.139.com",                 "port": 993},
    "yeah.net":             {"host": "imap.yeah.net",                "port": 993},
    "wp.pl":                {"host": "imap.wp.pl",                   "port": 993},
    "o2.pl":                {"host": "poczta.o2.pl",                 "port": 993},
    "interia.pl":           {"host": "poczta.interia.pl",            "port": 993},
    "onet.pl":              {"host": "imap.poczta.onet.pl",          "port": 993},
    "virgilio.it":          {"host": "imap.virgilio.it",             "port": 993},
    "libero.it":            {"host": "imapmail.libero.it",           "port": 993},
    "tin.it":               {"host": "imap.tin.it",                  "port": 993},
    "alice.it":             {"host": "imap.alice.it",                "port": 993},
    "tiscali.it":           {"host": "imap.tiscali.it",              "port": 993},
    "terra.com.br":         {"host": "imap.terra.com.br",            "port": 993},
    "bol.com.br":           {"host": "imap.bol.com.br",              "port": 993},
    "uol.com.br":           {"host": "imap.uol.com.br",              "port": 993},
    "ig.com.br":            {"host": "imap.ig.com.br",               "port": 993},
}

# Patterns tried for unknown domains (in order)
FALLBACK_PATTERNS = [
    "imap.{domain}",
    "mail.{domain}",
    "imap.mail.{domain}",
    "{domain}",
]
